name: Build and test
on: [ push ]

jobs:
  nix-ci:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: master
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
